"""
Binary Output Reader for Fokker-Planck Simulation

Reads .bin files generated by the simulation and converts them to
numpy arrays or plots them.

Binary format:
- Each file contains alternating (position, value) double pairs
- Position is in the same units as the simulation grid
- Value is the concentration or density field value

Usage:
    # Read and plot
    python read_binary_output.py data/pz_100D_N100_30_08_2022_betan_para_1.bin

    # Read and save as CSV
    python read_binary_output.py data/pz_100D_N100_30_08_2022_betan_para_1.bin --csv output.csv

    # Read multiple files and compare
    python read_binary_output.py file1.bin file2.bin --plot
"""

import numpy as np
import argparse
import sys
from pathlib import Path


def read_binary_file(filename):
    """
    Read binary simulation output file.

    Args:
        filename: Path to .bin file

    Returns:
        tuple: (positions, values) as numpy arrays
    """
    try:
        # Read all doubles from file
        data = np.fromfile(filename, dtype=np.float64)

        # Split into position and value arrays
        # Format is: pos1, val1, pos2, val2, ...
        positions = data[0::2]
        values = data[1::2]

        return positions, values

    except Exception as e:
        print(f"Error reading {filename}: {e}", file=sys.stderr)
        sys.exit(1)


def save_as_csv(positions, values, output_file):
    """Save data as CSV file."""
    import csv

    with open(output_file, "w", newline="") as f:
        writer = csv.writer(f, delimiter="\t")
        writer.writerow(["Position", "Value"])
        for pos, val in zip(positions, values):
            writer.writerow([pos, val])

    print(f"Saved to {output_file}")


def plot_data(files, labels=None):
    """Plot one or more binary files."""
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print(
            "Error: matplotlib not installed. Install with: pip install matplotlib",
            file=sys.stderr,
        )
        sys.exit(1)

    plt.figure(figsize=(10, 6))

    for i, filename in enumerate(files):
        positions, values = read_binary_file(filename)
        label = labels[i] if labels else Path(filename).stem
        plt.plot(positions, values, label=label, marker="o", markersize=2)

    plt.xlabel("Position")
    plt.ylabel("Value")
    plt.title("Simulation Output")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()


def print_statistics(positions, values, filename):
    """Print statistics about the data."""
    print(f"\n=== Statistics for {filename} ===")
    print(f"Number of points: {len(positions)}")
    print(f"Position range: [{positions.min():.6e}, {positions.max():.6e}]")
    print(f"Value range: [{values.min():.6e}, {values.max():.6e}]")
    print(f"Mean value: {values.mean():.6e}")
    print(f"Std deviation: {values.std():.6e}")
    print(f"Max value at position: {positions[values.argmax()]:.6e}")
    print(f"Min value at position: {positions[values.argmin()]:.6e}")


def main():
    parser = argparse.ArgumentParser(
        description="Read and analyze binary simulation output",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    parser.add_argument("files", nargs="+", help="Binary file(s) to read")
    parser.add_argument("--csv", help="Save as CSV file")
    parser.add_argument("--plot", action="store_true", help="Plot the data")
    parser.add_argument("--stats", action="store_true", help="Print statistics")
    parser.add_argument("--labels", nargs="+", help="Labels for plot legend")

    args = parser.parse_args()

    # Single file operations
    if len(args.files) == 1:
        filename = args.files[0]
        positions, values = read_binary_file(filename)

        if args.csv:
            save_as_csv(positions, values, args.csv)
        elif args.plot:
            plot_data([filename])
        elif args.stats:
            print_statistics(positions, values, filename)
        else:
            # Default: print first and last few values
            print(f"File: {filename}")
            print(f"Total points: {len(positions)}\n")
            print("First 5 points:")
            print("Position\tValue")
            for i in range(min(5, len(positions))):
                print(f"{positions[i]:.6e}\t{values[i]:.6e}")
            if len(positions) > 10:
                print("\n...\n")
                print("Last 5 points:")
                for i in range(len(positions) - 5, len(positions)):
                    print(f"{positions[i]:.6e}\t{values[i]:.6e}")

            print(f"\nUse --stats for statistics or --plot to visualize")

    # Multiple file operations
    else:
        if args.plot:
            plot_data(args.files, args.labels)
        else:
            # Print statistics for all files
            for filename in args.files:
                positions, values = read_binary_file(filename)
                print_statistics(positions, values, filename)


if __name__ == "__main__":
    main()
